# _config.yml

# -- Site Settings --
title: "Choo Jun Jie"
description: "Quantitative Researcher | Data Engineer | My Journey into Psychology"
url: "https://junjiechoo24.github.io"

# -- Theme & Skin --
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt"

# -- Author Info in Sidebar (Following Official Documentation) --
author:
  name: "Choo Jun Jie"
  # The | allows for multi-line content.
  bio: |
    Quantitative researcher applying statistical modeling and data science to the psychological sciences.
    
    <h3 class="author__bio-title">Education</h3>
    <p>
      MS Statistics, University of Chicago<br>
      BSc Mathematics & Statistics, University of Warwick
    </p>
  location: "Singapore"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:junjie.choo2404@hotmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/junjiechoo96"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/junjiechoo24"

# -- Defaults for Pages --
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_author_profile: true

# -- Font Settings --
google_fonts:
  - name: "Lora"
    weights: "400,700,400italic,700italic"
  - name: "Source Sans Pro"
    weights: "400,700,400italic,700italic"
