# _config.yml

# -- Site Settings --
title: ""
description: "Quantitative Researcher | Data Engineer | My Journey into Psychology"
url: "https://junjiechoo24.github.io"

# -- Theme & Skin --
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt"

# -- Author Info in Sidebar --
author:
  name: "Profile"
  bio: |
    Experienced data professional with a background in statistical modelling and engineering, now pivoting my focus toward research in the psychological sciences. I am passionate about understanding the whys and hows of the human condition.
    
    <h3 class="author__name" style="margin-top: 2em;">Education</h3>
    <p style="margin-bottom: 0.5em;">
      <b>MS Statistics</b><br>
      <em>University of Chicago</em>
    </p>
    <p>
      <b>BSc Mathematics & Statistics</b><br>
      <em>University of Warwick</em>
    </p>
  location: "Singapore"
  links:
    - label: "junjie.choo2404 (at) hotmail (dot) com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:junjie.choo2404@hotmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/junjiechoo96"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/junjiechoo24"
      
# -- Defaults for Pages --
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_author_profile: true

# -- Font Settings --
google_fonts:
  - name: "Lora"
    weights: "400,700,400italic,700italic"
  - name: "Source Sans Pro"
    weights: "400,700,400italic,700italic"
    
collections:
  projects:
    output: true
    permalink: /projects/:path/
