# .github/workflows/build-jekyll.yml

name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # or master, depending on your branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby, Jekyll, and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Minimal Mistakes theme requires Ruby 3.x
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
